### ISSUE TITLE
Removing physics should be separate button

### ISSUE THREAD

**Issue by biltzerpos** [LePa-YU/Visualizer#1] opened 2022-11-07 17:49 UTC
Branch: main
The "add physics interactivity" checkbox enables a large set of parameters. The user needs to scroll quite a bit down to disable physics. The check box should just enable/disable physics. Another button can enable the large set of parameters.

**Comment by mbaljko** [comment] 2022-11-07 21:12
IMO, the issue is that the checkbox label "add physics interactivity" is inaccurate - the checkbox enables/disables the _physics interactivity parameter panel_, and then one of the options within the panel is under the heading "physics" with a checkbox "enabled"
so the checkbox needs to correspond to a sub-option within the entire _physics interactivity parameter panel_

**Comment by biltzerpos** [comment] 2022-11-08 01:52
Agreed. Not sure if this option will be part of the UI for the design jam, so we can come back to this at a later time.

**Comment by ElmiraOn** [comment] 2022-11-08 04:36
it is definitely possible to have two different panels. it's just a matter of a checkbox and using an if statement to replace the panel. these options are mostly for development purposes. we can use them to see what options we want pyvis to have. after making changes we can generate the options by clicking on the ` generate option` button and copy-paste it into our code as a default layout.

**Comment by ElmiraOn** [comment] 2023-02-10 08:53
Since we are unlikely to add the physics options from pyvis to the visualizer, I will close this issue for now. we can always reopen it if needed later :)

**Closed by ElmiraOn** 2023-02-10 08:53 UTC
